[package]
name = "dioxus-helmet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { git = "https://github.com/dioxuslabs/dioxus" }

[dev-dependencies]

dioxus = { git = "https://github.com/dioxuslabs/dioxus", features = ["ssr"] }
# wasm-bindgen = "0.2.80"
# wasm-bindgen-test = "0.3.30"
# gloo-utils = "0.1.3"


[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
