[package]
name = "dioxus-helmet"
version = "0.2.0"
authors = ["Saicu"]
edition = "2021"
description = "Small Dioxus component which allows you to place elements in the head of your document"
license = "MIT"
repository = "https://github.com/saicu/dioxus-helmet"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false

[dependencies]
dioxus = "0.2.4"
web-sys = { version = "0.3.59", features = ["Document", "Window", "Element", "HtmlHeadElement", "HtmlCollection", "NamedNodeMap"] }
log = "0.4.17"
wasm-logger = "0.2.0"
js-sys = "0.3.59"
wasm-bindgen = "0.2.82"
lazy_static = "1.4.0"

[dev-dependencies]
# wasm-bindgen = "0.2.80"
# wasm-bindgen-test = "0.3.30"
# gloo-utils = "0.1.3"
